const PRODUCTS = [
  {
    id: "sk-01",
    name: "Hydrating Serum",
    category: "skincare",
    price: 52.0,
    rating: 4.7,
    reviews: 118,
    image: "serum.jpg",
    alt: "Bottle of Peavelle Hydrating Serum",
    badges: ["new"],
  },
  {
    id: "sk-02",
    name: "Gentle Cleanser",
    category: "skincare",
    price: 28.0,
    rating: 4.6,
    reviews: 94,
    image: "cleanser.jpg",
    alt: "Tube of Peavelle Gentle Cleanser",
  },
  {
    id: "sk-03",
    name: "Silk Moisturizer",
    category: "skincare",
    price: 46.0,
    rating: 4.8,
    reviews: 142,
    image: "moisturizer.jpg",
    alt: "Jar of Peavelle Silk Moisturizer",
  },
  {
    id: "sk-04",
    name: "Nourishing Face Cream",
    category: "skincare",
    price: 49.0,
    rating: 4.7,
    reviews: 101,
    image: "facecream.jpg",
    alt: "Jar of Peavelle Nourishing Face Cream",
  },
  {
    id: "sk-05",
    name: "Purifying Facewash",
    category: "skincare",
    price: 24.0,
    rating: 4.5,
    reviews: 76,
    image: "facewash.jpg",
    alt: "Bottle of Peavelle Purifying Facewash",
  },
  {
    id: "sk-06",
    name: "Daily Sunscreen SPF 50",
    category: "skincare",
    price: 32.0,
    rating: 4.9,
    reviews: 165,
    image: "sunscreen.jpg",
    alt: "Tube of Peavelle Daily Sunscreen SPF 50",
  },
  {
    id: "sk-07",
    name: "Clay Facial Mask",
    category: "skincare",
    price: 36.0,
    rating: 4.6,
    reviews: 88,
    image: "face mask.jpg",
    alt: "Jar of Peavelle Clay Facial Mask",
    badges: ["new"],
  },
  {
    id: "mu-01",
    name: "Rose Blush",
    category: "makeup",
    price: 26.0,
    rating: 4.6,
    reviews: 73,
    image: "blush.jpg",
    alt: "Compact of Peavelle Rose Blush",
  },
  {
    id: "mu-02",
    name: "Radiant Concealer",
    category: "makeup",
    price: 24.0,
    rating: 4.7,
    reviews: 109,
    image: "concealer.jpg",
    alt: "Tube of Peavelle Radiant Concealer",
  },
  {
    id: "mu-03",
    name: "Velvet Foundation",
    category: "makeup",
    price: 42.0,
    rating: 4.8,
    reviews: 156,
    image: "foundation.jpg",
    alt: "Bottle of Peavelle Velvet Foundation",
  },
  {
    id: "mu-04",
    name: "Precision Eyeliner",
    category: "makeup",
    price: 19.0,
    rating: 4.5,
    reviews: 64,
    image: "eyeliner.jpg",
    alt: "Peavelle Precision Eyeliner pen",
  },
  {
    id: "mu-05",
    name: "Balancing Toner",
    category: "makeup",
    price: 22.0,
    rating: 4.4,
    reviews: 57,
    image: "toner.jpg",
    alt: "Bottle of Peavelle Balancing Toner",
  },
  {
    id: "mu-06",
    name: "Shimmer Eye Shadow",
    category: "makeup",
    price: 28.0,
    rating: 4.7,
    reviews: 98,
    image: "eyeshadow.jpg",
    alt: "Palette of Peavelle Shimmer Eye Shadow",
    badges: ["new"],
  },
  {
    id: "mu-07",
    name: "Pro Brush Set",
    category: "makeup",
    price: 38.0,
    rating: 4.9,
    reviews: 132,
    image: "makeup brush.jpg",
    alt: "Set of Peavelle Pro makeup brushes",
    badges: ["new"],
  },
  {
    id: "lc-01",
    name: "Pink Whisper Lipstick",
    category: "lip-collection",
    price: 22.0,
    rating: 4.6,
    reviews: 84,
    image: "pink lipstick.jpg",
    alt: "Peavelle Pink Whisper Lipstick",
  },
  {
    id: "lc-02",
    name: "Nude Silk Lipstick",
    category: "lip-collection",
    price: 22.0,
    rating: 4.7,
    reviews: 91,
    image: "nude.jpg",
    alt: "Peavelle Nude Silk Lipstick",
  },
  {
    id: "lc-03",
    name: "Dark Nude Lipstick",
    category: "lip-collection",
    price: 22.0,
    rating: 4.5,
    reviews: 68,
    image: "darknude.jpg",
    alt: "Peavelle Dark Nude Lipstick",
  },
  {
    id: "lc-04",
    name: "Classic Red Lipstick",
    category: "lip-collection",
    price: 24.0,
    rating: 4.9,
    reviews: 147,
    image: "red.jpg",
    alt: "Peavelle Classic Red Lipstick",
    badges: ["new"],
  },
  {
    id: "lc-05",
    name: "Dark Red Lipstick",
    category: "lip-collection",
    price: 24.0,
    rating: 4.6,
    reviews: 79,
    image: "darkred.jpg",
    alt: "Peavelle Dark Red Lipstick",
  },
  {
    id: "lc-06",
    name: "Sheer Lip Gloss",
    category: "lip-collection",
    price: 18.0,
    rating: 4.5,
    reviews: 72,
    image: "lip gloss.jpg",
    alt: "Peavelle Sheer Lip Gloss",
    badges: ["new"],
  },
  {
    id: "lc-07",
    name: "Precision Lip Liner",
    category: "lip-collection",
    price: 16.0,
    rating: 4.4,
    reviews: 51,
    image: "lip liner.jpg",
    alt: "Peavelle Precision Lip Liner",
  },
  {
    id: "fr-01",
    name: "Vanilla Bloom Eau de Parfum",
    category: "fragrance",
    price: 68.0,
    rating: 4.7,
    reviews: 103,
    image: "vanilla.jpg",
    alt: "Bottle of Peavelle Vanilla Bloom Eau de Parfum",
  },
  {
    id: "fr-02",
    name: "Chocolate Mystique Eau de Parfum",
    category: "fragrance",
    price: 72.0,
    rating: 4.6,
    reviews: 82,
    image: "chocolate.jpg",
    alt: "Bottle of Peavelle Chocolate Mystique Eau de Parfum",
  },
  {
    id: "fr-03",
    name: "Floral Whisper Eau de Parfum",
    category: "fragrance",
    price: 64.0,
    rating: 4.8,
    reviews: 119,
    image: "floral fragrance.jpg",
    alt: "Bottle of Peavelle Floral Whisper Eau de Parfum",
  },
  {
    id: "fr-04",
    name: "Romantic Rose Eau de Parfum",
    category: "fragrance",
    price: 70.0,
    rating: 4.7,
    reviews: 96,
    image: "romantic.jpg",
    alt: "Bottle of Peavelle Romantic Rose Eau de Parfum",
  },
  {
    id: "fr-05",
    name: "Temptation Eau de Parfum",
    category: "fragrance",
    price: 76.0,
    rating: 4.9,
    reviews: 138,
    image: "temptation.jpg",
    alt: "Bottle of Peavelle Temptation Eau de Parfum",
    badges: ["new"],
  },
  {
    id: "fr-06",
    name: "Clean Linen Eau de Parfum",
    category: "fragrance",
    price: 58.0,
    rating: 4.5,
    reviews: 67,
    image: "clean.jpg",
    alt: "Bottle of Peavelle Clean Linen Eau de Parfum",
  },
  {
    id: "fr-07",
    name: "Fruity Blossom Eau de Parfum",
    category: "fragrance",
    price: 62.0,
    rating: 4.6,
    reviews: 74,
    image: "fruitty.jpg",
    alt: "Bottle of Peavelle Fruity Blossom Eau de Parfum",
  },
  {
    id: "bs-01",
    name: "Radiance Serum",
    category: "skincare",
    price: 54.0,
    rating: 4.8,
    reviews: 128,
    image: "radiance serum.jpg",
    alt: "Bottle of Peavelle Radiance Serum",
    badges: ["bestseller"],
  },
  {
    id: "bs-02",
    name: "Velvet Lipstick",
    category: "lip-collection",
    price: 32.0,
    rating: 5.0,
    reviews: 96,
    image: "velvet lipstick.jpg",
    alt: "Peavelle Velvet Lipstick",
    badges: ["bestseller"],
  },
  {
    id: "bs-03",
    name: "Luminous Foundation",
    category: "makeup",
    price: 48.0,
    rating: 4.9,
    reviews: 112,
    image: "luminous foundation.jpg",
    alt: "Bottle of Peavelle Luminous Foundation",
    badges: ["bestseller"],
  },
  {
    id: "bs-04",
    name: "Eau de Parfum Signature",
    category: "fragrance",
    price: 68.0,
    rating: 4.7,
    reviews: 87,
    image: "bestseller perfume.jpg",
    alt: "Bottle of Peavelle Eau de Parfum Signature",
    badges: ["bestseller"],
  },
  {
    id: "bs-05",
    name: "Glow Moisturizer",
    category: "skincare",
    price: 42.0,
    rating: 4.6,
    reviews: 103,
    image: "glow moisturizer.jpg",
    alt: "Jar of Peavelle Glow Moisturizer",
    badges: ["bestseller"],
  },
];

function getNewArrivals() {
  return PRODUCTS.filter((p) => p.badges && p.badges.includes("new"));
}

function getBestSellers() {
  return PRODUCTS.filter((p) => p.badges && p.badges.includes("bestseller"));
}

function getByCategory(category) {
  return PRODUCTS.filter(
    (p) =>
      p.category === category && !(p.badges && p.badges.includes("bestseller")),
  );
}
